name : exp19
n_splits : 5
target_col : health

params:
  objective : multiclass
  num_class : 3
  metric : custom
  learning_rate: 0.01
  boosting: gbdt
  seed: 42
  num_leaves: 32
  max_depth: -1
  feature_fraction : 0.9
  seed : 42

train_params :
  num_boost_round : 10000
  early_stopping_rounds : 100
  verbose_eval : 100

run_params : # Trueならtrain['health'].value_counts()[i]
  model1_under_sampling :
    zero : 0.38 # 5/13
    one : 0.54 # 7/13
    twe : 0.08 # 1/13
  model2_under_sampling :
    zero : 1
    one : 1
    twe : 1

ensemble_num : 10
target_encoding_type : jame # jame or cat
target_switch_num : 5
